### ISSUE TITLE
[MAYA-108122] Camera doesn't have a viewport representation when sublayered

### ISSUE THREAD

**Issue by Viele** [Autodesk/maya-usd#1451]
**Describe the bug**
Importing a camera from a usd file works as expected
However when sublayering the same file, there is no viewport representation of the camera
The camera data is there though. I am not sure if this is a known issue but I couldn't find anything about this 

**Steps to reproduce**
1. In a new scene hit "Create stage from file"
2. Select attached usd file
3. Data loads and can be selected in the outliner, but is not visible in viewport

**Expected behavior**
A selectable camera should be visible in the viewport

**Attachments**
Simple file with a single camera moving up over 20 frames
[maya_camera.zip](https://github.com/Autodesk/maya-usd/files/6585141/maya_camera.zip)

**Specs (if applicable):**
 - Win10
 - Maya 2022
 - Plugin v 0.9.0

**Comment by williamkrick** [comment]
You are correct, MayaUSD doesn't have support for drawing USD camera's in the viewport yet. I have logged logged this issue internally as MAYA-108122.

**Comment by neilrubie** [comment]
Hi there, just curious if this is still on the table. I'm unable to see the viewport representations of USD cameras. Would be great to have.

**Comment by santosg87** [comment]
Hi @neilrubie, this is something we will still have to discuss, due to the priority on all the other work we are getting to. Moving this to the backlog for now. we will re-visit it soon.

**Comment by santosg87** [comment]
Just an update for this. the changes required for this would also affect the Maya side. 

this would be something that would be in line with future releases of Maya. :)

**Comment by santosg87** [comment]
this issue is fixed on the latest release of Maya. note that this will require installing Maya 2023.2 in order to have the fix, as the changes are in maya code as well.

marking this one closed for now

**Comment by Narann** [comment]
I’ve tested with 2023.3 and the camera still does not show: [test.usd.json](https://github.com/Autodesk/maya-usd/files/15038376/test.usd.json)

(`.json` added to be able to joint the file)

![image](https://github.com/Autodesk/maya-usd/assets/659708/1c5bf139-450a-4123-8a28-b82e37e51d24)

**Comment by santosg87** [comment]
@Narann just one thing to check here: in order for this workflow to work on 2023, we had to introduce a new plugin to draw cameras, due to some limitations. are you able to confirm you have the "drawUfe" loaded?

<img width="1006" alt="Screenshot 2024-04-19 at 9 56 46 AM" src="https://github.com/Autodesk/maya-usd/assets/3026529/c235da98-db58-46fd-824b-4996e5d8066d">

**Comment by Narann** [comment]
Wow ! I didn’t know that! It works! Thanks and sorry for the noise!
