### ISSUE TITLE
UFE Unable to transform prims that use TransformationOps

### ISSUE THREAD

**Issue by radon199** [Autodesk/maya-usd#157]
Hey,

We are writing our prim transforms into USD as transformation matrixs, and when trying to transform these using the UFE SceneItems we get an error from USD about Xform compatibility.

`Warning: in SetTranslate at line 701 of /sw/dev/rousselp/src/MTCR/usd/build/platform-linux/arch-x86_64/os-CentOS-7/boost-1.61.0/python-2.7/maya_usd_stub/maya-2019/usd/src/usd/pxr/usd/lib/usdGeom/xformCommonAPI.cpp -- XformCommonAPI: Attempted to SetTranslate on an incompatible xformable </hotelLobby/env_hotelLobby_GRP/env_hotelLobby_vase>.
Failed to translate prim |world|mayaUsdProxy1|mayaUsdProxyShape1/hotelLobby/env_hotelLobby_GRP/env_hotelLobby_vase - Incompatible xform op xformOp:transform:
	File: /sw/dev/rousselp/src/MTCR/maya_usd/build/platform-linux/arch-x86_64/os-CentOS-7/boost-1.61.0/python-2.7/maya-2019/maya_usd_stub/usd-19.11.m2/maya_usd/src/maya_usd/lib/ufe/private/Utils.cpp
	Line: 147
	Function: translateOp
std:: Exception in ::notify handler:  Incompatible xform op xformOp:transform:
`

It looks like maybe the Transform Op is not supported by the common API? We could switch over to authoring the TRS directly but it worked well enough for us with transformation matrixs so far.

**Comment by ppt-adsk** [comment]
Hi Colin,

Can you post what the list of xform ops looks like for that prim?  The fairly restrictive nature of the USD xform common API has been something we've been discussing, so having a sense of what people are authoring in terms of xform ops that don't map to the common API would be helpful.

Cheers.

**Comment by radon199** [comment]
Hey,

It's very simple, we use the MakeMatrixXform() function on the UsdGeomXform schema to which 

That gives us this : overwrites the xformOpOrder attribute and sets a single TransformOp to the given 4x4 matrix.
`            matrix4d xformOp:transform = ( (0.958226371664042, 0, -0.28601087505122114, 0), (0, 1, 0, 0), (0.28601087505122114, 0, 0.958226371664042, 0), (67.51460433673371, 6.9672495747065195, 35.5943972489805, 1) )
            uniform token[] xformOpOrder = ["xformOp:transform"]`

In order to set a new transform in a higher layer we simply call MakeMatrixXform again with a new matrix. This authors a new XformOpOrder and transform Op and completely overwrites the lower layers matrix.
Currently with the Pixar plugin we move prims by making a temporary proxy set with the same xform as the prim, we move that around as much as we want and then confirm the transform back to USD. This means we read and write the matrix once which is actually really performant for us in huge scenes.

It looks like the CommonApi is attempting to keep the Ops from the lower layers, and copys them to the XformOpOrder in the new layer, but then that invalidates the CommonApi.

What you might be able to do is see if the Xformable has a TransformOp and if so overwrite with a Translate Rotate and Scale broken out form that matrix. Then you can use the CommonApi on top of that and it should be none the wiser about the TransformOp down below.

**Comment by robthebloke** [comment]
We've actually got a PR that fixes this issue (and provides support for animated transforms - which UFE also doesn't support right now). Getting the PR up for review is next on my todo list...

**Comment by radon199** [comment]
That would be great to see. Thanks!

**Comment by williamkrick** [comment]
I can reproduce something similar in MayaUSD when I use the translate manip and attempt to translate an instanced prim:

```
Failed to translate prim ***The prim name***
 - Incompatible xform op xformOp:translate:rotatePivotTranslate:
	File: C:\dev\usd\ecg-maya-usd\maya-usd\lib\mayaUsd\ufe\private\Utils.cpp
	Line: 146
	Function: MayaUsd_v0::ufe::translateOp
```

**Comment by cfmoore007** [comment]
@robthebloke / @wtelford - are there any updates on this ?  This is a major blocker for us to adopt UFE.
Thanks.

**Comment by wtelford** [comment]
There aren't any updates on this other than it is a hot topic for discussion. I really want to gather requirements and expectations around this concern.

**Comment by kxl-adsk** [comment]
@radon199 I don't know if you have access to the beta, but this issue should be fixed as of PR121. The work on improving ufe manipulation was merged to dev with https://github.com/Autodesk/maya-usd/pull/962. Please validate and close this ticket.

**Comment by radon199** [comment]
Were currently trying to get beta access, so I can test once we have that.

Just to clarify this is only available with UFE2 yes?

I ask because we still face having to switch to the CommonAPI in the mean time until the beta is released and is stable in production.

**Comment by santosd** [comment]
Hello @radon199 all manipulation improvements are available in Maya 2022. Please take a look and let us know if you run into any issues. For the time being we will close this ticket out.
