### ISSUE TITLE
[MAYA-122119] Group Options: Group pivot center and origin seem flipped

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#1949]
**Describe the bug**
Under Edit->Group options box, it appears that the group pivot center and group pivot origin behaviours are flipped. Selecting center seems to set the group's pivot to the origin and vice-versa.  

**Steps to reproduce**
1. Open a new file in Maya 2022
2. Navigate to Create -> Universal Scene Description (USD) -> Stage with new layer
3. Right click on the proxy shape -> Add new prim -> Capsule
4. Set Capsule's tx=5
5. Select the Capsule
5. Navigate to Edit->Group and choose options
6. Set to group under: parent, **group pivot: origin** and enable preserve position
7. Click apply. Notice that the pivot is centered at the capsule and the group's pivots have been updated. We would expect the group to be at the origin (the behaviour when grouping a native maya object).
![group_origin](https://user-images.githubusercontent.com/12554015/148122688-fb474e3b-89b8-4831-a676-968c3b906625.gif)

Repeat steps 1-5. 
6. Set to group under: parent, **group pivot: center** and enable preserve position
7. Click apply. Notice that the pivot is centered at the origin. We would expect the group to be centered around the capsule and update the pivots (the behaviour when grouping a native maya object).
![group_center](https://user-images.githubusercontent.com/12554015/148122988-a7be384f-c3a0-4b7b-a184-a42752f87426.gif)

**Expected behavior**
We would expect it to behave the same as native maya.

**Specs (if applicable):**
 - maya2022.update3
 - Maya Usd: dev at 04f2c94

Logged at Pixar as MAYA-3185

**Comment by santosd** [comment]
Thank you for reporting this @gracekumagai I was able to repro and logged it internally as MAYA-122119.

**Comment by santosg87** [comment]
this issue should be fixed on the latest builds. Note that this fix required Maya changes, so a new version of Maya will be necessary to see the fix.

**Comment by dj-mcg** [comment]
It appears that in 2023.3, Group pivot: origin now works as expected, but Group pivot: Center is still broken (ie. they now do the same thing). Does this require 2024?
