### ISSUE TITLE
USD Selection Mode for geometry

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#2440]
Currently there is no USD Selection Mode that will select the geometry that was clicked on. My first assumption was that this should be the behavior of the selection mode (none), but this appears to also select the Model. I'd suggest either changing this to select the mesh node which contains the geometry that would clicked on, or adding another built-in selection mode for "Geometry" or "Mesh"

**Comment by womanyoyoyo-adsk** [comment]
Your first assumption is correct - Selection Mode = (None) should select geometry.

**Comment by womanyoyoyo-adsk** [comment]
@santosg87 I cannot repro on MayaUSD: 202206281904, Maya: 202206271515. I know this was a problem in earlier cuts however. Can you please verify that this is now fixed?

**Comment by dj-mcg** [comment]
FWIW, I'm on latest MayaUsd code but on Maya 202205052215

**Comment by dj-mcg** [comment]
BTW this is still happening for me in Maya 2023.2 and latest mayaUsd dev...

**Comment by tanant** [comment]
well, you know, not a thumbs up as in good way, but thanks for confirming

**Comment by santosg87** [comment]
@dj-mcg would you be able to include a sample file that contains the typing on a prim causing the behavior you mention? most of the files we have tested with seem to behave pretty much as you described, when using "none" - so i am a bit curious on what we are missing.

What is the use for the workflow you have that is not being met? :)

**Comment by wallworm** [comment]
@dj-mcg We looked into this again and using Selection Mode set to None are selecting a Mesh when you set the Selection Mode to None. Can you send us a sample scene?

**Comment by dj-mcg** [comment]
Hi, sorry for the delay @wallworm. I can use the kitchen set to demonstrate this problem. If I have the USD selection mode set to (None) and select one of the "decorations" on the fridge via the viewport (try the blue M magnet), I'll end up with Refridgerator_1 selected as opposed to .../Refridgerator_1/Geom/Decorations/Letters/pPlane154

**Comment by womanyoyoyo-adsk** [comment]
Thanks for the repro steps. @wallworm I still can't repro. Looks like somehow @dj-mcg's selection mode is still set to kind=component.  Maybe we test on a cut of Maya 2023.2?

**Comment by wallworm** [comment]
@dj-mcg  After more investigation, I think that the problem reported here deals with a problem in the UI for selection mode. The USD Selection Mode incorrectly divides some options as Point Instances options, but those items do affect selection in all cases. If selection mode is set to Instances, the selection will never select instance proxies. So if you want to select a mesh under an instanceable prim, you need to set the USD Display Mode under Point Instances to Prototypes. We have discussed internally and see that we need to redesign the USD Selection Mode UI.
