### ISSUE TITLE
[MAYA-128888] UDIM does not work on 0.23 plugin

### ISSUE THREAD

**Issue by kimuss** [Autodesk/maya-usd#3016]
**Describe the bug**
If I open a new main stage with USD preview surface (from houdini), the texture with UDIM token does not showed correctly

**Specs (if applicable):**
 - OS & version Windows 11
 - Maya version Maya 2024
 - Maya USD 0.23 plugin

**Additional context**
- any previous plugin works correctly (0.22 on Maya 2022, 0.22 on Maya 2023)
- same view error with 0.23 on Maya 2023

**Comment by kimuss** [comment]
hello, 
thank you for your feedback, this is the picture with the problem
![test_UDIM](https://user-images.githubusercontent.com/54888290/231711408-dabc04d7-dfdb-485e-a490-319957b5c535.jpg)

**Comment by santosd** [comment]
Got it. Thanks @kimuss I am able to repro the issue on my end. I will log this internally so that we can have a look and see about fixing it.

**Comment by santosd** [comment]
I have logged this internally and we have it scheduled to be looked at and hopefully fixed by a dev. Thank you @kimuss for reporting this,. MAYA-128888

**Comment by DanEnglesson** [comment]
Hi,

I just want to check in on this as we still see this issue.
It works in MtH(storm) and usdviewer but not in VP2.

Specs
```
Centos 7.9
Maya 2022.4
maya-usd 0.23.0
Own build of USD 21.11
```

Cheers,
Dan
